Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"

  config.vm.define "vm#1" do |vm_config|
    vm_config.vm.hostname = "vm1" # Set hostnames for easier identification

    vm_config.vm.provider "qemu" do |qe|
      qe.arch = "x86_64"
      qe.machine = "q35"
      qe.cpu = "max"
      qe.net_device = "virtio-net-pci"
      qe.ssh_port = 50022
    end
  end
end